// angular-parcel/src/app/app.component.ts
import { Component } from '@angular/core';
import { singleSpaPropsSubject } from 'src/single-spa/single-spa-props';

@Component({
  selector: 'app-parcel',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public props$ = singleSpaPropsSubject;
  title = 'angular-parcel';
}

<section>
  <!-- Angular Parcel component is mounted! -->
  Parcel component with {{ (props$ | async)?.name }} is mounted!
  <br />
  Passed props from Parent
  <div style="color: red">{{ (props$ | async)?.customProp1 }}</div>
</section>

// vue-parcel/src/App.vue
<template>
  <section>
    Parcel component with {{ name }} is mounted!
    <br />
    Passed props from Parent
    <div style="color: red">{{ customProp1 }}</div>
  </section>
</template>

<script>
export default {
  name: "RootParcel",
  props: ["name", "customProp1", "mountParcel", "singleSpa"],
};
</script>
